In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler,MinMaxScaler
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score,accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier
from sklearn.tree import DecisionTreeClassifier, plot_tree,export_text
import matplotlib.pyplot as plt
from sklearn.neural_network import MLPClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.feature_selection import RFE
import numpy as np
from sklearn.feature_selection import RFECV
from sklearn.model_selection import StratifiedKFold
from sklearn.decomposition import PCA


c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/attr_value.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/tensor.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/cor

OPIS SKUPA PODATAKA

The dataset consists of 10 numerical and 8 categorical attributes.
The 'Revenue' attribute can be used as the class label.

"Administrative", "Administrative Duration", "Informational", "Informational Duration", "Product Related" and "Product Related Duration" represent the number of different types of pages visited by the visitor in that session and total time spent in each of these page categories. The values of these features are derived from the URL information of the pages visited by the user and updated in real time when a user takes an action, e.g. moving from one page to another. The "Bounce Rate", "Exit Rate" and "Page Value" features represent the metrics measured by "Google Analytics" for each page in the e-commerce site. The value of "Bounce Rate" feature for a web page refers to the percentage of visitors who enter the site from that page and then leave ("bounce") without triggering any other requests to the analytics server during that session. The value of "Exit Rate" feature for a specific web page is calculated as for all pageviews to the page, the percentage that were the last in the session. The "Page Value" feature represents the average value for a web page that a user visited before completing an e-commerce transaction. The "Special Day" feature indicates the closeness of the site visiting time to a specific special day (e.g. Mother’s Day, Valentine's Day) in which the sessions are more likely to be finalized with transaction. The value of this attribute is determined by considering the dynamics of e-commerce such as the duration between the order date and delivery date. For example, for Valentina’s day, this value takes a nonzero value between February 2 and February 12, zero before and after this date unless it is close to another special day, and its maximum value of 1 on February 8. The dataset also includes operating system, browser, region, traffic type, visitor type as returning or new visitor, a Boolean value indicating whether the date of the visit is weekend, and month of the year.

In [3]:
def metrika(title,preds,y_test):
    print(title, accuracy_score(y_test,preds))
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, preds))
    print("\nClassification Report:")
    print(classification_report(y_test, preds))
    print("-------------------------------------------------------------------")

In [4]:
df = pd.read_csv(r'podaci\online+shoppers+purchasing+intention+dataset\online_shoppers_intention preprocessed.csv', encoding='cp1252', sep=',')
print(df.columns)

Index(['Administrative', 'Administrative_Duration', 'Informational',
       'Informational_Duration', 'ProductRelated', 'ProductRelated_Duration',
       'BounceRates', 'ExitRates', 'PageValues', 'SpecialDay', 'Month',
       'OperatingSystems', 'Browser', 'Region', 'TrafficType', 'VisitorType',
       'Weekend', 'Revenue'],
      dtype='object')


In [5]:
df.head()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,2,1,1,1,1,2,0,0
1,0,0.0,0,0.0,2,64.000000,0.00,0.10,0.0,0.0,2,2,2,1,2,2,0,0
2,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,2,4,1,9,3,2,0,0
3,0,0.0,0,0.0,2,2.666667,0.05,0.14,0.0,0.0,2,3,2,2,4,2,0,0
4,0,0.0,0,0.0,10,627.500000,0.02,0.05,0.0,0.0,2,3,3,1,4,2,1,0


In [6]:
X = df.drop("Revenue", axis=1)
y = df["Revenue"]

In [7]:
engagement_features = ["Administrative","Administrative_Duration","Informational","Informational_Duration","ProductRelated",
        "ProductRelated_Duration","BounceRates","ExitRates","PageValues"]

technical_features = ["OperatingSystems", "Browser", "Region", "TrafficType", "VisitorType"]

time_features = ["SpecialDay","Month","Weekend"]

feature_names = X.columns

In [8]:
numeric_features = [
    "Administrative", "Administrative_Duration",
    "Informational", "Informational_Duration",
    "ProductRelated", "ProductRelated_Duration",
    "BounceRates", "ExitRates", "PageValues"
]

In [9]:
pca = PCA(n_components=2)
scaler = MinMaxScaler()

In [10]:
X_sca = scaler.fit_transform(X)
X_pca = pca.fit_transform(X_sca)

In [11]:
X_eng_sca = scaler.fit_transform(X[engagement_features])
X_eng_pca = pca.fit_transform(X_eng_sca)

In [12]:
X_tec_sca = scaler.fit_transform(X[technical_features])
X_tec_pca = pca.fit_transform(X_tec_sca)

In [13]:
X_time_sca = scaler.fit_transform(X[time_features])
X_time_pca = pca.fit_transform(X_time_sca)

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=123, stratify=y)
X_train_pca, X_test_pca, y_train_pca, y_test_pca = train_test_split(X_pca, y, test_size=0.2, random_state=123, stratify=y)
X_train_sca, X_test_sca, y_train_sca, y_test_sca = train_test_split(X_sca, y, test_size=0.2, random_state=123, stratify=y)
X_train_eng, X_test_eng, y_train_eng, y_test_eng = train_test_split(X_eng_pca, y, test_size=0.2, random_state=123, stratify=y)
X_train_tec, X_test_tec, y_train_tec, y_test_tec = train_test_split(X_tec_pca, y, test_size=0.2, random_state=123, stratify=y)
X_train_time, X_test_time, y_train_time, y_test_time = train_test_split(X_time_pca, y, test_size=0.2, random_state=123, stratify=y)

In [ ]:
dt = DecisionTreeClassifier()

dt.fit(X_train, y_train)
preds = dt.predict(X_test)
metrika("Stablo odlucivanja + X_test",preds,y_test)

dt.fit(X_train_pca, y_train_pca)
preds = dt.predict(X_test_pca)
metrika("Stablo odlucivanja + X_test_pca",preds,y_test_pca)

dt.fit(X_train_sca, y_train_sca)
preds = dt.predict(X_test_sca)
metrika("Stablo odlucivanja + X_test_sca",preds,y_test_sca)

dt.fit(X_train_eng, y_train_eng)
preds = dt.predict(X_test_eng)
metrika("Stablo odlucivanja + X_test_eng",preds,y_test_eng)

dt.fit(X_train_tec, y_train_tec)
preds = dt.predict(X_test_tec)
metrika("Stablo odlucivanja + X_test_tec",preds,y_test_tec)

dt.fit(X_train_time, y_train_time)
preds = dt.predict(X_test_time)
metrika("Stablo odlucivanja + X_test_time",preds,y_test_time)

# plt.figure(figsize=(20,10))
# plot_tree(dt, feature_names=X.columns, class_names=["No", "Yes"], filled=True)
# plt.title("Decision Tree")
# plt.show()

Stablo odlucivanja + X_test 0.8532035685320357
Confusion Matrix:
[[1882  202]
 [ 160  222]]

Classification Report:
              precision    recall  f1-score   support

           0       0.92      0.90      0.91      2084
           1       0.52      0.58      0.55       382

    accuracy                           0.85      2466
   macro avg       0.72      0.74      0.73      2466
weighted avg       0.86      0.85      0.86      2466

-------------------------------------------------------------------
Stablo odlucivanja + X_test_pca 0.7712895377128953
Confusion Matrix:
[[1798  286]
 [ 278  104]]

Classification Report:
              precision    recall  f1-score   support

           0       0.87      0.86      0.86      2084
           1       0.27      0.27      0.27       382

    accuracy                           0.77      2466
   macro avg       0.57      0.57      0.57      2466
weighted avg       0.77      0.77      0.77      2466

------------------------------------------

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(av

In [16]:
dt = DecisionTreeClassifier()

dt.fit(X_train, y_train)
preds = dt.predict(X_test)
metrika("Stablo odlucivanja + X_test",preds,y_test)

dt.fit(X_train_pca, y_train_pca)
preds = dt.predict(X_test_pca)
metrika("Stablo odlucivanja + X_test_pca",preds,y_test_pca)

dt.fit(X_train_sca, y_train_sca)
preds = dt.predict(X_test_sca)
metrika("Stablo odlucivanja + X_test_sca",preds,y_test_sca)

dt.fit(X_train_eng, y_train_eng)
preds = dt.predict(X_test_eng)
metrika("Stablo odlucivanja + X_test_eng",preds,y_test_eng)

dt.fit(X_train_tec, y_train_tec)
preds = dt.predict(X_test_tec)
metrika("Stablo odlucivanja + X_test_tec",preds,y_test_tec)

dt.fit(X_train_time, y_train_time)
preds = dt.predict(X_test_time)
metrika("Stablo odlucivanja + X_test_time",preds,y_test_time)

# plt.figure(figsize=(20,10))
# plot_tree(dt, feature_names=X.columns, class_names=["No", "Yes"], filled=True)
# plt.title("Decision Tree")
# plt.show()

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Stablo odlucivanja + X_test 0.8544201135442011
Confusion Matrix:
[[1888  196]
 [ 163  219]]

Classification Report:
              precision    recall  f1-score   support

           0       0.92      0.91      0.91      2084
           1       0.53      0.57      0.55       382

    accuracy                           0.85      2466
   macro avg       0.72      0.74      0.73      2466
weighted avg       0.86      0.85      0.86      2466

-------------------------------------------------------------------
Stablo odlucivanja + X_test_pca 0.7672343876723439
Confusion Matrix:
[[1790  294]
 [ 280  102]]

Classification Report:
              precision    recall  f1-score   support

           0       0.86      0.86      0.86      2084
           1       0.26      0.27      0.26       382

    accuracy                           0.77      2466
   macro avg       0.56      0.56      0.56      2466
weighted avg       0.77      0.77      0.77      2466

------------------------------------------

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [17]:
rf = RandomForestClassifier()

rf.fit(X_train, y_train)
preds = rf.predict(X_test)
metrika("rf + X_test",preds,y_test)

rf.fit(X_train_pca, y_train_pca)
preds = rf.predict(X_test_pca)
metrika("rf + X_test_pca",preds,y_test_pca)

rf.fit(X_train_sca, y_train_sca)
preds = rf.predict(X_test_sca)
metrika("rf + X_test_sca",preds,y_test_sca)

rf.fit(X_train_eng, y_train_eng)
preds = rf.predict(X_test_eng)
metrika("rf + X_test_eng",preds,y_test_eng)

rf.fit(X_train_tec, y_train_tec)
preds = rf.predict(X_test_tec)
metrika("rf + X_test_tec",preds,y_test_tec)

rf.fit(X_train_time, y_train_time)
preds = rf.predict(X_test_time)
metrika("rf + X_test_time",preds,y_test_time)

rf + X_test 0.9047039740470397
Confusion Matrix:
[[2009   75]
 [ 160  222]]

Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.96      0.94      2084
           1       0.75      0.58      0.65       382

    accuracy                           0.90      2466
   macro avg       0.84      0.77      0.80      2466
weighted avg       0.90      0.90      0.90      2466

-------------------------------------------------------------------
rf + X_test_pca 0.8183292781832928
Confusion Matrix:
[[1977  107]
 [ 341   41]]

Classification Report:
              precision    recall  f1-score   support

           0       0.85      0.95      0.90      2084
           1       0.28      0.11      0.15       382

    accuracy                           0.82      2466
   macro avg       0.56      0.53      0.53      2466
weighted avg       0.76      0.82      0.78      2466

-------------------------------------------------------------------
rf + X

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(av

In [18]:
mlp = MLPClassifier(hidden_layer_sizes=(10,), max_iter=1000)

mlp.fit(X_train, y_train)
preds = mlp.predict(X_test)
metrika("Mlp + X_test",preds,y_test)

mlp.fit(X_train_pca, y_train_pca)
preds = mlp.predict(X_test_pca)
metrika("Mlp + X_test_pca",preds,y_test_pca)

mlp.fit(X_train_sca, y_train_sca)
preds = mlp.predict(X_test_sca)
metrika("Mlp + X_test_sca",preds,y_test_sca)

mlp.fit(X_train_eng, y_train_eng)
preds = mlp.predict(X_test_eng)
metrika("Mlp + X_test_eng",preds,y_test_eng)

mlp.fit(X_train_tec, y_train_tec)
preds = mlp.predict(X_test_tec)
metrika("Mlp + X_test_tec",preds,y_test_tec)

mlp.fit(X_train_time, y_train_time)
preds = mlp.predict(X_test_time)
metrika("Mlp + X_test_time",preds,y_test_time)

Mlp + X_test 0.8868613138686131
Confusion Matrix:
[[2013   71]
 [ 208  174]]

Classification Report:
              precision    recall  f1-score   support

           0       0.91      0.97      0.94      2084
           1       0.71      0.46      0.56       382

    accuracy                           0.89      2466
   macro avg       0.81      0.71      0.75      2466
weighted avg       0.88      0.89      0.88      2466

-------------------------------------------------------------------
Mlp + X_test_pca 0.8450932684509327
Confusion Matrix:
[[2084    0]
 [ 382    0]]

Classification Report:
              precision    recall  f1-score   support

           0       0.85      1.00      0.92      2084
           1       0.00      0.00      0.00       382

    accuracy                           0.85      2466
   macro avg       0.42      0.50      0.46      2466
weighted avg       0.71      0.85      0.77      2466

-------------------------------------------------------------------


c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(av

Mlp + X_test_sca 0.8994322789943228
Confusion Matrix:
[[1991   93]
 [ 155  227]]

Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.96      0.94      2084
           1       0.71      0.59      0.65       382

    accuracy                           0.90      2466
   macro avg       0.82      0.77      0.79      2466
weighted avg       0.89      0.90      0.90      2466

-------------------------------------------------------------------
Mlp + X_test_eng 0.8446877534468775
Confusion Matrix:
[[2083    1]
 [ 382    0]]

Classification Report:
              precision    recall  f1-score   support

           0       0.85      1.00      0.92      2084
           1       0.00      0.00      0.00       382

    accuracy                           0.84      2466
   macro avg       0.42      0.50      0.46      2466
weighted avg       0.71      0.84      0.77      2466

-------------------------------------------------------------------


c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(av

              precision    recall  f1-score   support

           0       0.85      1.00      0.92      2084
           1       0.00      0.00      0.00       382

    accuracy                           0.85      2466
   macro avg       0.42      0.50      0.46      2466
weighted avg       0.71      0.85      0.77      2466

-------------------------------------------------------------------
Mlp + X_test_time 0.8450932684509327
Confusion Matrix:
[[2084    0]
 [ 382    0]]

Classification Report:
              precision    recall  f1-score   support

           0       0.85      1.00      0.92      2084
           1       0.00      0.00      0.00       382

    accuracy                           0.85      2466
   macro avg       0.42      0.50      0.46      2466
weighted avg       0.71      0.85      0.77      2466

-------------------------------------------------------------------


c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(av

In [19]:
nb = GaussianNB()

nb.fit(X_train, y_train)
preds = nb.predict(X_test)
metrika("nb + X_test",preds,y_test)

nb.fit(X_train_pca, y_train_pca)
preds = nb.predict(X_test_pca)
metrika("nb + X_test_pca",preds,y_test_pca)

nb.fit(X_train_sca, y_train_sca)
preds = nb.predict(X_test_sca)
metrika("nb + X_test_sca",preds,y_test_sca)

nb.fit(X_train_eng, y_train_eng)
preds = nb.predict(X_test_eng)
metrika("nb + X_test_eng",preds,y_test_eng)

nb.fit(X_train_tec, y_train_tec)
preds = nb.predict(X_test_tec)
metrika("nb + X_test_tec",preds,y_test_tec)

nb.fit(X_train_time, y_train_time)
preds = nb.predict(X_test_time)
metrika("nb + X_test_time",preds,y_test_time)

nb + X_test 0.8467153284671532
Confusion Matrix:
[[1875  209]
 [ 169  213]]

Classification Report:
              precision    recall  f1-score   support

           0       0.92      0.90      0.91      2084
           1       0.50      0.56      0.53       382

    accuracy                           0.85      2466
   macro avg       0.71      0.73      0.72      2466
weighted avg       0.85      0.85      0.85      2466

-------------------------------------------------------------------
nb + X_test_pca 0.8450932684509327
Confusion Matrix:
[[2084    0]
 [ 382    0]]

Classification Report:
              precision    recall  f1-score   support

           0       0.85      1.00      0.92      2084
           1       0.00      0.00      0.00       382

    accuracy                           0.85      2466
   macro avg       0.42      0.50      0.46      2466
weighted avg       0.71      0.85      0.77      2466

-------------------------------------------------------------------
nb + X

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(av

In [20]:
knn = KNeighborsClassifier(n_neighbors=3)

knn.fit(X_train, y_train)
preds = knn.predict(X_test)
metrika("knn + X_test",preds,y_test)

knn.fit(X_train_pca, y_train_pca)
preds = knn.predict(X_test_pca)
metrika("knn + X_test_pca",preds,y_test_pca)

knn.fit(X_train_sca, y_train_sca)
preds = knn.predict(X_test_sca)
metrika("knn + X_test_sca",preds,y_test_sca)

knn.fit(X_train_eng, y_train_eng)
preds = knn.predict(X_test_eng)
metrika("knn + X_test_eng",preds,y_test_eng)

knn.fit(X_train_tec, y_train_tec)
preds = knn.predict(X_test_tec)
metrika("knn + X_test_tec",preds,y_test_tec)

knn.fit(X_train_time, y_train_time)
preds = knn.predict(X_test_time)
metrika("knn + X_test_time",preds,y_test_time)

knn + X_test 0.8540145985401459
Confusion Matrix:
[[1965  119]
 [ 241  141]]

Classification Report:
              precision    recall  f1-score   support

           0       0.89      0.94      0.92      2084
           1       0.54      0.37      0.44       382

    accuracy                           0.85      2466
   macro avg       0.72      0.66      0.68      2466
weighted avg       0.84      0.85      0.84      2466

-------------------------------------------------------------------
knn + X_test_pca 0.8049472830494728
Confusion Matrix:
[[1933  151]
 [ 330   52]]

Classification Report:
              precision    recall  f1-score   support

           0       0.85      0.93      0.89      2084
           1       0.26      0.14      0.18       382

    accuracy                           0.80      2466
   macro avg       0.56      0.53      0.53      2466
weighted avg       0.76      0.80      0.78      2466

-------------------------------------------------------------------
knn 

In [21]:
lr = LogisticRegression()

lr.fit(X_train, y_train)
preds = lr.predict(X_test)
metrika("lr + X_test",preds,y_test)

lr.fit(X_train_pca, y_train_pca)
preds = lr.predict(X_test_pca)
metrika("lr + X_test_pca",preds,y_test_pca)

lr.fit(X_train_sca, y_train_sca)
preds = lr.predict(X_test_sca)
metrika("lr + X_test_sca",preds,y_test_sca)

lr.fit(X_train_eng, y_train_eng)
preds = lr.predict(X_test_eng)
metrika("lr + X_test_eng",preds,y_test_eng)

lr.fit(X_train_tec, y_train_tec)
preds = lr.predict(X_test_tec)
metrika("lr + X_test_tec",preds,y_test_tec)

lr.fit(X_train_time, y_train_time)
preds = lr.predict(X_test_time)
metrika("lr + X_test_time",preds,y_test_time)

lr + X_test 0.884022708840227
Confusion Matrix:
[[2029   55]
 [ 231  151]]

Classification Report:
              precision    recall  f1-score   support

           0       0.90      0.97      0.93      2084
           1       0.73      0.40      0.51       382

    accuracy                           0.88      2466
   macro avg       0.82      0.68      0.72      2466
weighted avg       0.87      0.88      0.87      2466

-------------------------------------------------------------------
lr + X_test_pca 0.8450932684509327
Confusion Matrix:
[[2084    0]
 [ 382    0]]

Classification Report:
              precision    recall  f1-score   support

           0       0.85      1.00      0.92      2084
           1       0.00      0.00      0.00       382

    accuracy                           0.85      2466
   macro avg       0.42      0.50      0.46      2466
weighted avg       0.71      0.85      0.77      2466

-------------------------------------------------------------------
lr + X_

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classif

In [22]:
svm = SVC(kernel='rbf', probability=True)

svm.fit(X_train, y_train)
preds = svm.predict(X_test)
metrika("svm + X_test",preds,y_test)

svm.fit(X_train_pca, y_train_pca)
preds = svm.predict(X_test_pca)
metrika("svm + X_test_pca",preds,y_test_pca)

svm.fit(X_train_sca, y_train_sca)
preds = svm.predict(X_test_sca)
metrika("svm + X_test_sca",preds,y_test_sca)

svm.fit(X_train_eng, y_train_eng)
preds = svm.predict(X_test_eng)
metrika("svm + X_test_eng",preds,y_test_eng)

svm.fit(X_train_tec, y_train_tec)
preds = svm.predict(X_test_tec)
metrika("svm + X_test_tec",preds,y_test_tec)

svm.fit(X_train_time, y_train_time)
preds = svm.predict(X_test_time)
metrika("svm + X_test_time",preds,y_test_time)

svm + X_test 0.8475263584752636
Confusion Matrix:
[[2083    1]
 [ 375    7]]

Classification Report:
              precision    recall  f1-score   support

           0       0.85      1.00      0.92      2084
           1       0.88      0.02      0.04       382

    accuracy                           0.85      2466
   macro avg       0.86      0.51      0.48      2466
weighted avg       0.85      0.85      0.78      2466

-------------------------------------------------------------------
svm + X_test_pca 0.8450932684509327
Confusion Matrix:
[[2084    0]
 [ 382    0]]

Classification Report:
              precision    recall  f1-score   support

           0       0.85      1.00      0.92      2084
           1       0.00      0.00      0.00       382

    accuracy                           0.85      2466
   macro avg       0.42      0.50      0.46      2466
weighted avg       0.71      0.85      0.77      2466

-------------------------------------------------------------------


c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(av

svm + X_test_sca 0.8815896188158961
Confusion Matrix:
[[2051   33]
 [ 259  123]]

Classification Report:
              precision    recall  f1-score   support

           0       0.89      0.98      0.93      2084
           1       0.79      0.32      0.46       382

    accuracy                           0.88      2466
   macro avg       0.84      0.65      0.70      2466
weighted avg       0.87      0.88      0.86      2466

-------------------------------------------------------------------
svm + X_test_eng 0.8450932684509327
Confusion Matrix:
[[2084    0]
 [ 382    0]]

Classification Report:
              precision    recall  f1-score   support

           0       0.85      1.00      0.92      2084
           1       0.00      0.00      0.00       382

    accuracy                           0.85      2466
   macro avg       0.42      0.50      0.46      2466
weighted avg       0.71      0.85      0.77      2466

-------------------------------------------------------------------


c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(av

svm + X_test_tec 0.8450932684509327
Confusion Matrix:
[[2084    0]
 [ 382    0]]

Classification Report:
              precision    recall  f1-score   support

           0       0.85      1.00      0.92      2084
           1       0.00      0.00      0.00       382

    accuracy                           0.85      2466
   macro avg       0.42      0.50      0.46      2466
weighted avg       0.71      0.85      0.77      2466

-------------------------------------------------------------------


c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(av

svm + X_test_time 0.8450932684509327
Confusion Matrix:
[[2084    0]
 [ 382    0]]

Classification Report:
              precision    recall  f1-score   support

           0       0.85      1.00      0.92      2084
           1       0.00      0.00      0.00       382

    accuracy                           0.85      2466
   macro avg       0.42      0.50      0.46      2466
weighted avg       0.71      0.85      0.77      2466

-------------------------------------------------------------------


c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(av

In [23]:
xgb = XGBClassifier(use_label_encoder=False, eval_metric='mlogloss')

xgb.fit(X_train, y_train)
preds = xgb.predict(X_test)
metrika("xgb + X_test",preds,y_test)

xgb.fit(X_train_pca, y_train_pca)
preds = xgb.predict(X_test_pca)
metrika("xgb + X_test_pca",preds,y_test_pca)

xgb.fit(X_train_sca, y_train_sca)
preds = xgb.predict(X_test_sca)
metrika("xgb + X_test_sca",preds,y_test_sca)

xgb.fit(X_train_eng, y_train_eng)
preds = xgb.predict(X_test_eng)
metrika("xgb + X_test_eng",preds,y_test_eng)

xgb.fit(X_train_tec, y_train_tec)
preds = xgb.predict(X_test_tec)
metrika("xgb + X_test_tec",preds,y_test_tec)

xgb.fit(X_train_time, y_train_time)
preds = xgb.predict(X_test_time)
metrika("xgb + X_test_time",preds,y_test_time)

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:183: UserWarning: [15:25:56] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:183: UserWarning: [15:25:56] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


xgb + X_test 0.902676399026764
Confusion Matrix:
[[1989   95]
 [ 145  237]]

Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.95      0.94      2084
           1       0.71      0.62      0.66       382

    accuracy                           0.90      2466
   macro avg       0.82      0.79      0.80      2466
weighted avg       0.90      0.90      0.90      2466

-------------------------------------------------------------------
xgb + X_test_pca 0.8418491484184915
Confusion Matrix:
[[2061   23]
 [ 367   15]]

Classification Report:
              precision    recall  f1-score   support

           0       0.85      0.99      0.91      2084
           1       0.39      0.04      0.07       382

    accuracy                           0.84      2466
   macro avg       0.62      0.51      0.49      2466
weighted avg       0.78      0.84      0.78      2466

-------------------------------------------------------------------


c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:183: UserWarning: [15:25:56] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:183: UserWarning: [15:25:57] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


xgb + X_test_sca 0.902676399026764
Confusion Matrix:
[[1989   95]
 [ 145  237]]

Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.95      0.94      2084
           1       0.71      0.62      0.66       382

    accuracy                           0.90      2466
   macro avg       0.82      0.79      0.80      2466
weighted avg       0.90      0.90      0.90      2466

-------------------------------------------------------------------
xgb + X_test_eng 0.8337388483373885
Confusion Matrix:
[[2027   57]
 [ 353   29]]

Classification Report:
              precision    recall  f1-score   support

           0       0.85      0.97      0.91      2084
           1       0.34      0.08      0.12       382

    accuracy                           0.83      2466
   macro avg       0.59      0.52      0.52      2466
weighted avg       0.77      0.83      0.79      2466

-------------------------------------------------------------------


c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:183: UserWarning: [15:25:57] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


xgb + X_test_tec 0.8414436334144363
Confusion Matrix:
[[2073   11]
 [ 380    2]]

Classification Report:
              precision    recall  f1-score   support

           0       0.85      0.99      0.91      2084
           1       0.15      0.01      0.01       382

    accuracy                           0.84      2466
   macro avg       0.50      0.50      0.46      2466
weighted avg       0.74      0.84      0.77      2466

-------------------------------------------------------------------
xgb + X_test_time 0.8450932684509327
Confusion Matrix:
[[2084    0]
 [ 382    0]]

Classification Report:
              precision    recall  f1-score   support

           0       0.85      1.00      0.92      2084
           1       0.00      0.00      0.00       382

    accuracy                           0.85      2466
   macro avg       0.42      0.50      0.46      2466
weighted avg       0.71      0.85      0.77      2466

-------------------------------------------------------------------

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:183: UserWarning: [15:25:57] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\U

In [24]:
# rules = export_text(dt, feature_names = X.columns.tolist())
# print("Decision Tree Rules:\n", rules)

# feature_selection(rules, X_train, y_train)

In [25]:
y_train_oh = to_categorical(y_train)
y_test_oh = to_categorical(y_test)

model = Sequential([
    Dense(64, input_shape=(X_train.shape[1],), activation='relu'),
    Dense(64, activation='relu'),
    Dense(2, activation='softmax')
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train_oh, epochs=50, batch_size=8, verbose=0)
_, acc = model.evaluate(X_test, y_test_oh, verbose=0)
print("Deep Learning Accuracy:", acc)

# feature_selection(model, X_train, y_train)

c:\Users\Korisnik\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Deep Learning Accuracy: 0.8868613243103027
